# Generated by Django 5.2 on 2025-04-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('bank', 'Chuyển khoản ngân hàng'), ('card', 'Thẻ ngân hàng')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('awaiting_shipment', 'Sắp được vận chuyển'), ('shipped', 'Đã vận chuyển')], default='pending', max_length=20),
        ),
    ]
