# Generated by Django 5.2 on 2025-04-30 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_question_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
