# Generated by Django 5.2 on 2025-04-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_product_review_roduct_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='roduct',
            new_name='product',
        ),
    ]
